package com.neu.pojo;
// Generated Apr 7, 2016 4:11:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import com.neu.pojo.Person;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name = "doctor", catalog = "webtools")
public class Doctor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5779732965161444522L;
	private long personId;
	private Person person;
	private String practiceNo;
	private String role;

	public Doctor() {
	}

	public Doctor(Person person) {
		this.person = person;
	}

	public Doctor(Person person, String practiceNo, String role) {
		this.person = person;
		this.practiceNo = practiceNo;
		this.role = role;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "person"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "PersonId", unique = true, nullable = false)
	public long getPersonId() {
		return this.personId;
	}

	public void setPersonId(long personId) {
		this.personId = personId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "PracticeNo", length = 20,unique=true)
	public String getPracticeNo() {
		return this.practiceNo;
	}

	public void setPracticeNo(String practiceNo) {
		this.practiceNo = practiceNo;
	}

	@Column(name = "Role", length = 200)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
