package com.neu.pojo;
// Generated Apr 9, 2016 10:44:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Publichealthofficer generated by hbm2java
 */
@Entity
@Table(name = "publichealthofficer", catalog = "webtools")
public class Publichealthofficer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4812039429840195559L;
	private long personId;
	private Person person;
	private String zipCodeOfficial;
	private String role;

	public Publichealthofficer() {
	}

	public Publichealthofficer(Person person) {
		this.person = person;
	}

	public Publichealthofficer(Person person, String zipCodeOfficial, String role) {
		this.person = person;
		this.zipCodeOfficial = zipCodeOfficial;
		this.role = role;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "person"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "PersonId", unique = true, nullable = false)
	public long getPersonId() {
		return this.personId;
	}

	public void setPersonId(long personId) {
		this.personId = personId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "zipCodeOfficial", length = 20)
	public String getZipCodeOfficial() {
		return this.zipCodeOfficial;
	}

	public void setZipCodeOfficial(String zipCodeOfficial) {
		this.zipCodeOfficial = zipCodeOfficial;
	}

	@Column(name = "Role", length = 200)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
