package com.neu.pojo;
// Generated Apr 9, 2016 10:44:56 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Statelist generated by hbm2java
 */
@Entity
@Table(name = "statelist", catalog = "webtools")
public class Statelist implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -489893396596706864L;
	private long stateId;
	private String stateName;
	private Set<Citylist> citylists = new HashSet<Citylist>(0);

	public Statelist() {
	}

	public Statelist(long stateId, String stateName) {
		this.stateId = stateId;
		this.stateName = stateName;
	}

	public Statelist(long stateId, String stateName, Set<Citylist> citylists) {
		this.stateId = stateId;
		this.stateName = stateName;
		this.citylists = citylists;
	}

	@Id

	@Column(name = "stateId", unique = true, nullable = false)
	public long getStateId() {
		return this.stateId;
	}

	public void setStateId(long stateId) {
		this.stateId = stateId;
	}

	@Column(name = "stateName", nullable = false, length = 200)
	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statelist")
	public Set<Citylist> getCitylists() {
		return this.citylists;
	}

	public void setCitylists(Set<Citylist> citylists) {
		this.citylists = citylists;
	}

}
