package com.neu.pojo;
// Generated Apr 9, 2016 10:44:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.neu.business.Auditable;

/**
 * Symptomslist generated by hbm2java
 */
@Entity
@Table(name = "symptomslist", catalog = "webtools")
public class Symptomslist implements java.io.Serializable,Auditable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2997736053535101071L;
	private long symptomsId;
	private String symptomsDescription;
	private String activeKey;
	private Date creationTime;
	private Date modifiedTime;
	private Set<Vitalsign> vitalSign;

	public Symptomslist() {
	}

	public Symptomslist(long symptomsId, Date creationTime, Date modifiedTime) {
		this.symptomsId = symptomsId;
		this.creationTime = creationTime;
		this.modifiedTime = modifiedTime;
	}

	public Symptomslist(long symptomsId, String symptomsDescription, String activeKey, Date creationTime,
			Date modifiedTime) {
		this.symptomsId = symptomsId;
		this.symptomsDescription = symptomsDescription;
		this.activeKey = activeKey;
		this.creationTime = creationTime;
		this.modifiedTime = modifiedTime;
	}

	@Id
	@GeneratedValue
	@Column(name = "SymptomsId", unique = true, nullable = false)
	public long getSymptomsId() {
		return this.symptomsId;
	}

	public void setSymptomsId(long symptomsId) {
		this.symptomsId = symptomsId;
	}

	@Column(name = "SymptomsDescription", length = 200)
	public String getSymptomsDescription() {
		return this.symptomsDescription;
	}

	public void setSymptomsDescription(String symptomsDescription) {
		this.symptomsDescription = symptomsDescription;
	}

	@Column(name = "ActiveKey", length = 1)
	public String getActiveKey() {
		return this.activeKey;
	}

	public void setActiveKey(String activeKey) {
		this.activeKey = activeKey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creationTime", nullable = false, length = 19)
	public Date getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Date creationTime) {
		this.creationTime = creationTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifiedTime", nullable = false, length = 19)
	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}
	@ManyToMany(mappedBy="symptomsList")
	public Set<Vitalsign> getVitalSign() {
		return vitalSign;
	}

	public void setVitalSign(Set<Vitalsign> vitalSign) {
		this.vitalSign = vitalSign;
	}
	
	

}
