package com.neu.pojo;
// Generated Apr 7, 2016 4:11:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.neu.business.Auditable;

/**
 * Useraccount generated by hbm2java
 */
@Entity
@Table(name = "useraccount", catalog = "webtools")
@org.hibernate.annotations.Entity(
		dynamicUpdate = true
)
public class Useraccount implements java.io.Serializable,Auditable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 522807195349942430L;
	private long userId;
	private Person person;
	private String userName;
	private String password;
	private String role;
	private Date creationTime;
	private Date modifiedTime;
	private Set<Workrequest> workrequests = new HashSet<Workrequest>(0);
	private Set<Logindetails> logindetailses = new HashSet<Logindetails>(0);
	

	public Useraccount() {
		
	}

	public Useraccount(long userId, Person person, Date creationTime, Date modifiedTime) {
		this.userId = userId;
		this.person = person;
		this.creationTime = creationTime;
		this.modifiedTime = modifiedTime;
	}

	public Useraccount(long userId, Person person, String userName, String password, String role, Date creationTime,
			Date modifiedTime,Set<Workrequest> workrequests, Set<Logindetails> logindetailses) {
		this.userId = userId;
		this.person = person;
		this.userName = userName;
		this.password = password;
		this.role = role;
		this.creationTime = creationTime;
		this.modifiedTime = modifiedTime;
		this.workrequests = workrequests;
		this.logindetailses = logindetailses;
	}

	
	@Id  
    @Column(name="UserID",unique = true, nullable = false)  
    @GeneratedValue(generator="gen")  
    @GenericGenerator(name="gen", strategy="foreign",   
    parameters=@Parameter(name="property", value="person"))
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@OneToOne  
    @PrimaryKeyJoinColumn 
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "UserName", length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Role", length = 20)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creationTime", nullable = false, length = 19)
	public Date getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Date creationTime) {
		this.creationTime = creationTime;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifiedTime", nullable = false, length = 19)
	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "useraccount")
	public Set<Workrequest> getWorkrequests() {
		return this.workrequests;
	}

	public void setWorkrequests(Set<Workrequest> workrequests) {
		this.workrequests = workrequests;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "useraccount")
	public Set<Logindetails> getLogindetailses() {
		return this.logindetailses;
	}

	public void setLogindetailses(Set<Logindetails> logindetailses) {
		this.logindetailses = logindetailses;
	}

}
